<?php
/** @var \Dev\Banner\Block\Template $block */

//var_dump($block->getData());

?>

<div class="template">
    <h1><?=$block->getName()?></h1>
</div>

<?php
  if(isset($_POST['id']))
  {
    $id = isset($_POST['id']);

  }
?>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>

<a href="<?= $block->getNewUrl()?>"> New </a>

<table border =1>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Brand</th>
    <th>Price</th>
    <th>Image</th>
    <th>Create At</th>
    <th>Update At</th>
    <th>Action</th> 
  </tr>
    <?php
        foreach ($block->getPostCollection() as $key=>$post){
            echo '<tr>
                    <td>'.$post->getPropId().'</td>
                    <td>'.$post->getName().'</td>
                    <td>'.$post->getBrand().'</td>
                    <td>'.$post->getPrice().'</td>
                    <td>'.$post->getImage().'</td>
                    <td>'.$post->getCreatedAt().'</td>
                    <td>'.$post->getUpdatedAt().'</td>
                    <td>
                    <!-- todo Add the functionality of Edit and Delete -->
                      <a href='.$block->getEditPageUrl().'id/'.$post->getData('prop_id').'> Edit </a>
                      <a href='.$block->getDeleteUrl($post->getData('prop_id')).'>Delete</a>
                    </td>
                  </tr>';
        }
    ?>
</table>

</body>
</html>
<?php
